---
title: "Proposal_01_test"
author: "Barbara Paradis"
date: "2026-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Title  <- c("Harry Potter and the Sorcerer's Stone", 
            "A Short History of Nearly Everything", 
            "Notes from a Small Island", 
            "The Lord of the Rings", 
            "Hatcher", 
            "The Changeling Sea",
            "The Known World", 
            "Traders, Guns & Money: Knowns and Unknowns in the Dazzling World of Derivatives",
            "Annals of the Former World", 
            "Rising from the Plains", 
            "Harry Potter and the Half-Blood Prince", 
            "Harry Potter and the Order of the Phoenix", 
            "Harry Potter and the Chamber of Secrets", 
            "Harry Potter and the Prisoner of Azkaban",
            "Harry Potter and the Goblet of Fire", 
            "The Great Gatsby",
            "To Kill a Mockingbird",
            "1984",
            "Pride and Prejudice",
            "The Catcher in the Rye",
            "The Hobbit",
            "Fahrenheit 451",
            "Animal Farm",
            "The Book Thief",
            "The Alchemist",
            "The Kite Runner",
            "Little Women",
            "Jane Eyre",
            "The Chronicles of Narnia",
            "The Hunger Games",
            "The Fault in Our Stars",
            "The Help",
            "Life of Pi",
            "The Da Vinci Code",
            "The Picture of Dorian Gray", 
            "The Midnight Library",
            "The Seven Husbands of Evelyn Hugo",
            "Where the Crawdads Sing",
            "The Silent Patient",
            "Educated",
            "Becoming",
            "The Girl on the Train",
            "Gone Girl",
            "The Handmaid's Tale",
            "The Road",
            "The Color Purple",
            "Beloved",
            "The Grapes of Wrath",
            "Of Mice and Men",
            "The Old Man and the Sea",
            "Brave New World",
            "Lord of the Flies",
            "The Stranger",
            "The Metamorphosis",
            "The Brothers Karamazov",
            "Crime and Punishment",
            "Anna Karenina",
            "The Count of Monte Cristo",
            "Les Misérables",
            "The Three Musketeers",
            "Dracula",
            "Frankenstein",
            "The Time Machine",
            "The War of the Worlds",
            "The Adventures of Huckleberry Finn",
            "The Adventures of Tom Sawyer",
            "The Scarlet Letter",
            "The Secret Garden",
            "A Little Princess",
            "The Wind in the Willows",
            "Alice's Adventures in Wonderland",
            "Through the Looking-Glass",
            "Peter Pan",
            "The Wonderful Wizard of Oz",
            "The Giver",
            "Divergent",
            "The Maze Runner",
            "Percy Jackson & the Olympians",
            "The Lightning Thief",
            "Eragon",
            "The Golden Compass",
            "The Princess Bride",
            "Good Omens",
            "The Hitchhiker's Guide to the Galaxy",
  "The Night Circus",
  "Station Eleven",
  "Cloud Atlas",
  "The Goldfinch",
  "The Book of Life",
  "The Ocean at the End of the Lane",
  "Neverwhere",
  "American Gods",
  "The House in the Cerulean Sea",
  "A Man Called Ove",
  "The Invisible Life of Addie LaRue",
  "The Song of Achilles",
  "Circe",
  "Normal People",
  "Little Fires Everywhere",
  "The Vanishing Half",
  "The Poppy War",
  "Red Rising",
  "The Name of the Wind",
  "Mistborn: The Final Empire"
            )
Author    <- c("J.K. Rowling", 
               "Bill Bryson", 
               "Bill Bryson", 
               "J.R.R. Tolkien", 
               "Gary Paulsen", 
               "Patricia A. McKillip",
               "Edward P. Jones",
               "Satyajit Das", 
               "John McPhee",
               "John McPhee",
               "J.K. Rowling",
               "J.K. Rowling", 
               "J.K. Rowling", 
               "J.K. Rowling", 
               "J.K. Rowling", 
               "F. Scott Fitzgerald",
               "Harper Lee",
               "George Orwell",
               "Jane Austen",
               "J.D. Salinger",
               "J.R.R. Tolkien",
               "Ray Bradbury",
               "George Orwell",
               "Markus Zusak",
               "Paulo Coelho",
               "Khaled Hosseini",
               "Louisa May Alcott",
               "Charlotte Brontë",
               "C.S. Lewis",
               "Suzanne Collins",
               "John Green",
               "Kathryn Stockett",
               "Yann Martel",
               "Dan Brown",
               "Oscar Wilde", 
               "Matt Haig",
               "Taylor Jenkins Reid",
               "Delia Owens",
               "Alex Michaelides",
              "Tara Westover",
              "Michelle Obama",
              "Paula Hawkins",
              "Gillian Flynn",
              "Margaret Atwood",
              "Cormac McCarthy",
              "Alice Walker",
              "Toni Morrison",
              "John Steinbeck",
              "John Steinbeck",
              "Ernest Hemingway",
              "Aldous Huxley",
              "William Golding",
              "Albert Camus",
              "Franz Kafka",
              "Fyodor Dostoevsky",
              "Fyodor Dostoevsky",
              "Leo Tolstoy",
              "Alexandre Dumas",
              "Victor Hugo",
              "Alexandre Dumas",
              "Bram Stoker",
              "Mary Shelley",
              "H.G. Wells",
              "H.G. Wells",
              "Mark Twain",
              "Mark Twain",
              "Nathaniel Hawthorne",
              "Frances Hodgson Burnett",
              "Frances Hodgson Burnett",
              "Kenneth Grahame",
              "Lewis Carroll",
              "Lewis Carroll",
              "J.M. Barrie",
              "L. Frank Baum",
              "Lois Lowry",
              "Veronica Roth",
              "James Dashner",
              "Rick Riordan",
              "Rick Riordan",
              "Christopher Paolini",
              "Philip Pullman",
              "William Goldman",
              "Neil Gaiman & Terry Pratchett",
              "Douglas Adams",
              "Erin Morgenstern",
              "Emily St. John Mandel",
              "David Mitchell",
              "Donna Tartt",
              "Deborah Harkness",
              "Neil Gaiman",
              "Neil Gaiman",
              "Neil Gaiman",
              "TJ Klune",
              "Fredrik Backman",
              "V.E. Schwab",
              "Madeline Miller",
              "Madeline Miller",
              "Sally Rooney",
              "Celeste Ng",
              "Brit Bennett",
              "R.F. Kuang",
              "Pierce Brown",
              "Patrick Rothfuss",
              "Brandon Sanderson")
Publication_Month <- c("June", 
                       "May", 
                       "September", 
                       "October", 
                       "September", 
                       "October", 
                       "September", 
                       "April", 
                       "June", 
                       "July", 
                       "June", 
                       "June", 
                       "July", 
                       "July", 
                       "July",
                       "April",
                       "July", 
                       "June", 
                       "January", 
                       "July", 
                       "September",  
                       "October",  
                       "August", 
                       "March", 
                       "May", 
                       "May",  
                       "September", 
                       "October",  
                       "October", 
                       "September", 
                       "January", 
                       "February", 
                       "May",  
                       "April", 
                       "July",
                       "September",
                       "June",
                        "August",
                        "January",
                        "August",
                        "November",
                        "January",
                        "May",
                        "June",
                        "September",
                        "June",
                        "September",
                        "April",
                        "December",
                        "September",
                        "April",
                        "October",
                        "November",
                        "November",
                        "November",
                        "January",
                        "March",
                        "August",
                        "June",
                        "March",
                        "May",
                        "January",
                        "November",
                        "July",
                        "December",
                        "November",
                        "March",
                        "September",
                        "September",
                        "June",
                        "November",
                        "January",
                        "December",
                        "May",
                        "April",
                        "May",
                        "October",
                        "June",
                        "June",
                        "August",
                        "October",
                        "September",
                        "May",
                        "April",
                        "September",
                        "May",
                        "August",
                        "February",
                        "June",
                        "June",
                        "September",
                        "March",
                        "March",
                        "August",
                        "September",
                        "August",
                        "April",
                        "August",
                        "May",
                        "June",
                        "April",
                        "January",
                        "March",
                        "July")
Publication_Year <- c(1997,
                      2003, 
                      1995, 
                      1955, 
                      1987, 
                      1988, 
                      2003, 
                      2006, 
                      1998, 
                      1998, 
                      2005, 
                      2003, 
                      1998, 
                      1999, 
                      2000, 
                      1925,
                      1960,
                      1949,
                      1813,
                      1951,
                      1937,
                      1953,
                      1945,
                      2005,
                      1988,
                      2003,
                      1868,
                      1847,
                      1950,
                      2008,
                      2012,
                      2009,
                      2001,
                      2003,
                      1890, 
                      2020,
                      2017,
                      2018,
                      2019,
                      2018,
                      2018,
                      2015,
                      2012,
                      1985,
                      2006,
                      1982,
                      1987,
                      1939,
                      1937,
                      1952,
                      1932,
                      1954,
                      1942,
                      1915,
                      1880,
                      1866,
                      1878,
                      1844,
                      1862,
                      1844,
                      1897,
                      1818,
                      1895,
                      1898,
                      1884,
                      1876,
                      1850,
                      1911,
                      1905,
                      1908,
                      1865,
                      1871,
                      1904,
                      1900,
                      1993,
                      2011,
                      2009,
                      2005,
                      2005,
                      2002,
                      1995,
                      1973,
                      1990,
                      1979,
                      2011,
                      2014,
                      2004,
                      2013,
                      2014,
                      2013,
                      1996,
                      2001,
                      2020,
                      2012,
                      2020,
                      2011,
                      2018,
                      2018,
                      2017,
                      2020,
                      2018,
                      2014,
                      2015,
                      2006)
Number_of_Ratings  <- c(7434783, 
                        316671, 
                        98212, 
                        586599, 
                        322595, 
                        5023, 
                        38299, 
                        38298, 
                        1698, 
                        3638, 
                        2553909, 
                        2631427, 
                        2878196, 
                        2972519, 
                        2725467, 
                        5000000,
                        5500000,
                        4800000,
                        4200000,
                        3400000,
                        2500000,
                        2300000,
                        2200000,
                        2100000,
                        2000000,
                        1900000,
                        1800000,
                        1700000,
                        1600000,
                        1500000,
                        1400000,
                        1300000,
                        1200000,
                        1100000,
                        1000000, 
                        1200000,
                        900000,
                        1000000,
                        850000,
                        700000,
                        650000,
                        900000,
                        1200000,
                        900000,
                        650000,
                        700000,
                        600000,
                        800000,
                        600000,
                        500000,
                        700000,
                        800000,
                        550000,
                        450000,
                        500000,
                        600000,
                        500000,
                        400000,
                        350000,
                        300000,
                        500000,
                        800000,
                        400000,
                        350000,
                        700000,
                        500000,
                        450000,
                        300000,
                        250000,
                        350000,
                        600000,
                        300000,
                        300000,
                        500000,
                        700000,
                        650000,
                        500000,
                        450000,
                        400000,
                        350000,
                        300000,
                        400000,
                        450000,
                        1500000,
                        450000,
                        350000,
                        400000,
                        500000,
                        250000,
                        300000,
                        400000,
                        700000,
                        200000,
                        500000,
                        250000,
                        400000,
                        350000,
                        300000,
                        300000,
                        200000,
                        150000,
                        300000,
                        500000,
                        450000)
Average_Rating  <- c(4.48, 
                     4.19, 
                     3.91, 
                     4.50, 
                     3.74, 
                     4.07, 
                     3.81, 
                     3.83, 
                     3.91, 
                     4.35, 
                     4.57, 
                     4.5, 
                     4.43, 
                     4.57, 
                     4.56, 
                     3.93,
                     4.26,
                     4.19,
                     4.28,
                     3.80,
                     4.27,
                     4.13,
                     3.98,
                     4.37,
                     3.91,
                     4.34,
                     4.12,
                     4.14,
                     4.25,
                     4.33,
                     4.15,
                     4.47,
                     3.92,
                     4.21,
                     4.07, 
                     4.15,
                     4.37,
                      4.40,
                      4.18,
                      4.47,
                      4.47,
                      3.96,
                      4.06,
                      4.17,
                      3.97,
                      4.21,
                      4.08,
                      3.96,
                      3.88,
                      3.98,
                      3.99,
                      3.92,
                      4.01,
                      4.01,
                      4.00,
                      4.33,
                      4.02,
                      4.22,
                      4.23,
                      4.21,
                      4.00,
                      3.84,
                      3.90,
                      3.82,
                      3.84,
                      3.91,
                      3.93,
                      4.13,
                      4.14,
                      4.06,
                      4.07,
                      4.06,
                      4.22,
                      4.00,
                      4.12,
                      4.14,
                      4.03,
                      4.26,
                      4.28,
                      4.30,
                      4.02,
                      4.26,
                      4.00,
                      4.22,
                      4.03,
                      3.92,
                      4.01,
                      3.95,
                      4.10,
                      4.09,
                      4.17,
                      4.11,
                      4.46,
                      4.36,
                      4.16,
                      4.39,
                      4.25,
                      3.87,
                      4.05,
                      4.13,
                      4.13,
                      4.26,
                      4.52,
                      4.46)

proposals_dataset <- data.frame(Title, Author, Publication_Month, Publication_Year, Number_of_Ratings, Average_Rating)
proposals_dataset <- proposals_dataset[order(proposals_dataset$Title), ]

head(proposals_dataset)
```

